In [1]:
import pandas as pd
import numpy as np

import technical_indicators as ti

In [2]:
import pandas_ta as ta
from ta.volume import VolumeWeightedAveragePrice

In [ ]:
# Making the data set with 
# Open High Low Close Volume EMA 100 EMA 200 VWAP RSI STOCHRSI_K STOCHRSI_D MACD

In [3]:
df = pd.read_csv('..\\raw_data_30m\\currency_pairs\\EURUSD_M30.csv',  sep='\t')

In [4]:
df = df.rename(columns={'Open':'open', 'High':'high', 'Low':'low', 'Close':'close', 'Volume':'volume'})

In [5]:
df = df[-100000:]
df.reset_index(inplace=True)
df = df.drop(['index', 'Time'],axis=1)

In [6]:
df.to_csv('ok.csv')

In [7]:
df = pd.read_csv('ok.csv')
df = df.drop('Unnamed: 0',axis=1)

In [9]:
# Getting EMA 
df = ti._ema_n(df, 100)
df = ti._ema_n(df, 200)

In [10]:
df = ti._ema_signal(df)

In [11]:
# VWAP
df = ti._vwap(df)

In [12]:
# df = ti._rsi(df)

In [13]:
df = ti._stochrsi(df)

In [14]:
df = ti._macd(df)
df['macd_signal'] = df['macd_signal'].astype(int)

In [15]:
df

,open,high,low,close,volume,ema_100,ema_200,ema_signal,vwap,vwap_signal,STOCHk_14_3_3,STOCHd_14_3_3,stochrsi_signal,MACD_12_26_9,MACDs_12_26_9,MACDh_12_26_9,macd_signal
0,1.13471,1.13485,1.13396,1.13422,1740,1.134220,1.134220,0,1.134343,-1,NaN,NaN,0,NaN,NaN,NaN,0
1,1.13423,1.13462,1.13316,1.13407,2365,1.134217,1.134219,0,1.134117,-1,NaN,NaN,0,NaN,NaN,NaN,0
2,1.13407,1.13583,1.13402,1.13563,4016,1.134245,1.134233,0,1.134633,-1,NaN,NaN,0,NaN,NaN,NaN,0
3,1.13563,1.13966,1.13562,1.13802,5377,1.134320,1.134270,1,1.136109,1,NaN,NaN,0,NaN,NaN,NaN,0
4,1.13803,1.13833,1.13617,1.13636,4333,1.134360,1.134291,0,1.136747,-1,NaN,NaN,0,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1.06736,1.06766,1.06709,1.06712,3963,1.072240,1.074366,-1,1.067112,-1,11.843782,9.664968,1,-0.001400,-0.001278,-0.000121,-1
99996,1.06712,1.06751,1.06680,1.06744,5103,1.072145,1.074297,-1,1.067256,-1,17.241379,13.503718,1,-0.001348,-0.001292,-0.000056,-1
99997,1.06742,1.06750,1.06709,1.06730,3513,1.072049,1.074227,-1,1.067276,-1,16.666667,15.250609,1,-0.001303,-0.001295,-0.000009,-1
99998,1.06732,1.06786,1.06731,1.06783,2894,1.071965,1.074163,-1,1.067369,-1,22.495895,18.801314,0,-0.001211,-0.001278,0.000066,1
99999,1.06785,1.06807,1.06766,1.06788,2410,1.071884,1.074101,-1,1.067575,-1,26.108374,21.756979,0,-0.001121,-0.001247,0.000125,1

In [18]:
df.dtypes

open               float64
high               float64
low                float64
close              float64
volume               int64
ema_100            float64
ema_200            float64
ema_signal           int64
vwap               float64
vwap_signal          int32
STOCHk_14_3_3      float64
STOCHd_14_3_3      float64
stochrsi_signal      int32
MACD_12_26_9       float64
MACDs_12_26_9      float64
MACDh_12_26_9      float64
macd_signal          int32
dtype: object

In [16]:
df = df.dropna()
df.reset_index(inplace=True)
df = df.drop('index',axis=1)

In [17]:
df

,open,high,low,close,volume,ema_100,ema_200,ema_signal,vwap,vwap_signal,STOCHk_14_3_3,STOCHd_14_3_3,stochrsi_signal,MACD_12_26_9,MACDs_12_26_9,MACDh_12_26_9,macd_signal
0,1.14767,1.14784,1.14724,1.14772,713,1.138854,1.136817,1,1.147701,-1,72.529313,75.162355,0,0.002632,0.002986,-0.000353,-1
1,1.14772,1.14784,1.14676,1.14680,1107,1.139011,1.136916,1,1.147502,-1,68.802345,71.936829,0,0.002427,0.002874,-0.000447,-1
2,1.14683,1.14738,1.14681,1.14705,1040,1.139171,1.137017,1,1.147230,-1,64.325753,68.552470,0,0.002258,0.002751,-0.000493,-1
3,1.14705,1.14705,1.14657,1.14680,1043,1.139322,1.137114,1,1.147009,-1,55.700296,62.942798,0,0.002080,0.002617,-0.000536,-1
4,1.14676,1.14724,1.14668,1.14722,1674,1.139478,1.137215,1,1.146989,-1,50.428720,56.818256,0,0.001951,0.002483,-0.000533,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99962,1.06736,1.06766,1.06709,1.06712,3963,1.072240,1.074366,-1,1.067112,-1,11.843782,9.664968,1,-0.001400,-0.001278,-0.000121,-1
99963,1.06712,1.06751,1.06680,1.06744,5103,1.072145,1.074297,-1,1.067256,-1,17.241379,13.503718,1,-0.001348,-0.001292,-0.000056,-1
99964,1.06742,1.06750,1.06709,1.06730,3513,1.072049,1.074227,-1,1.067276,-1,16.666667,15.250609,1,-0.001303,-0.001295,-0.000009,-1
99965,1.06732,1.06786,1.06731,1.06783,2894,1.071965,1.074163,-1,1.067369,-1,22.495895,18.801314,0,-0.001211,-0.001278,0.000066,1
99966,1.06785,1.06807,1.06766,1.06788,2410,1.071884,1.074101,-1,1.067575,-1,26.108374,21.756979,0,-0.001121,-0.001247,0.000125,1

In [19]:
print(df.columns.to_list)

<bound method IndexOpsMixin.tolist of Index(['open', 'high', 'low', 'close', 'volume', 'ema_100', 'ema_200',
       'ema_signal', 'vwap', 'vwap_signal', 'STOCHk_14_3_3', 'STOCHd_14_3_3',
       'stochrsi_signal', 'MACD_12_26_9', 'MACDs_12_26_9', 'MACDh_12_26_9',
       'macd_signal'],
      dtype='object')>

In [20]:
# Define the function to calculate the trend
def get_trend(df):
    # Calculate the percentage change in price for the current candlestick and the next 14 candlesticks
    pct_change = df['close'].pct_change(periods=7)
    
    # Initialize the trend column with 0 (neutral)
    df['trend'] = 0
    
    # Set the trend to 1 (up) if the price is up by 0.2% or more in any of the next 14 candlesticks
    df.loc[pct_change >= 0.002, 'trend'] = 1
    
    # Set the trend to -1 (down) if the price is down by 0.2% or more in any of the next 14 candlesticks
    df.loc[pct_change <= -0.002, 'trend'] = -1
    
    return df

get_trend(df)

,open,high,low,close,volume,ema_100,ema_200,ema_signal,vwap,vwap_signal,STOCHk_14_3_3,STOCHd_14_3_3,stochrsi_signal,MACD_12_26_9,MACDs_12_26_9,MACDh_12_26_9,macd_signal,trend
0,1.14767,1.14784,1.14724,1.14772,713,1.138854,1.136817,1,1.147701,-1,72.529313,75.162355,0,0.002632,0.002986,-0.000353,-1,0
1,1.14772,1.14784,1.14676,1.14680,1107,1.139011,1.136916,1,1.147502,-1,68.802345,71.936829,0,0.002427,0.002874,-0.000447,-1,0
2,1.14683,1.14738,1.14681,1.14705,1040,1.139171,1.137017,1,1.147230,-1,64.325753,68.552470,0,0.002258,0.002751,-0.000493,-1,0
3,1.14705,1.14705,1.14657,1.14680,1043,1.139322,1.137114,1,1.147009,-1,55.700296,62.942798,0,0.002080,0.002617,-0.000536,-1,0
4,1.14676,1.14724,1.14668,1.14722,1674,1.139478,1.137215,1,1.146989,-1,50.428720,56.818256,0,0.001951,0.002483,-0.000533,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99962,1.06736,1.06766,1.06709,1.06712,3963,1.072240,1.074366,-1,1.067112,-1,11.843782,9.664968,1,-0.001400,-0.001278,-0.000121,-1,-1
99963,1.06712,1.06751,1.06680,1.06744,5103,1.072145,1.074297,-1,1.067256,-1,17.241379,13.503718,1,-0.001348,-0.001292,-0.000056,-1,0
99964,1.06742,1.06750,1.06709,1.06730,3513,1.072049,1.074227,-1,1.067276,-1,16.666667,15.250609,1,-0.001303,-0.001295,-0.000009,-1,0
99965,1.06732,1.06786,1.06731,1.06783,2894,1.071965,1.074163,-1,1.067369,-1,22.495895,18.801314,0,-0.001211,-0.001278,0.000066,1,0
99966,1.06785,1.06807,1.06766,1.06788,2410,1.071884,1.074101,-1,1.067575,-1,26.108374,21.756979,0,-0.001121,-0.001247,0.000125,1,0

In [22]:
df.to_csv("main_df_period_7.csv")