In [1]:
import pandas as pd
import numpy as np

import technical_indicators as ti

In [2]:
import pandas_ta as ta
from ta.volume import VolumeWeightedAveragePrice

In [ ]:
# Making the data set with 
# Open High Low Close Volume EMA 100 EMA 200 VWAP RSI STOCHRSI_K STOCHRSI_D MACD

In [3]:
df = pd.read_csv('..\\raw_data_30m\\currency_pairs\\EURUSD_M30.csv',  sep='\t')

In [48]:
df = df.rename(columns={'Open':'open', 'High':'high', 'Low':'low', 'Close':'close', 'Volume':'volume'})

In [49]:
df = df[-100000:]
df.reset_index(inplace=True)
df = df.drop(['index', 'Time'],axis=1)

In [21]:
df.to_csv('ok.csv')

In [2]:
df = pd.read_csv('ok.csv')
df = df.drop('Unnamed: 0',axis=1)

In [6]:
# Getting EMA 
df = ti._ema_n(df, 100)
df = ti._ema_n(df, 200)

In [7]:
df = ti._ema_signal(df)

In [8]:
# VWAP
df = ti._vwap(df)

In [10]:
# df = ti._rsi(df)

In [3]:
df = ti._stochrsi(df)

In [9]:
df

,open,high,low,close,volume,STOCHk_14_3_3,STOCHd_14_3_3,stochrsi_signal,ema_100,ema_200,ema_signal,vwap,vwap_signal
0,1.13471,1.13485,1.13396,1.13422,1740,NaN,NaN,0,1.134220,1.134220,0,1.134343,-1
1,1.13423,1.13462,1.13316,1.13407,2365,NaN,NaN,0,1.134217,1.134219,0,1.134117,-1
2,1.13407,1.13583,1.13402,1.13563,4016,NaN,NaN,0,1.134245,1.134233,0,1.134633,-1
3,1.13563,1.13966,1.13562,1.13802,5377,NaN,NaN,0,1.134320,1.134270,1,1.136109,1
4,1.13803,1.13833,1.13617,1.13636,4333,NaN,NaN,0,1.134360,1.134291,0,1.136747,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1.06736,1.06766,1.06709,1.06712,3963,11.843782,9.664968,1,1.072240,1.074366,-1,1.067112,-1
99996,1.06712,1.06751,1.06680,1.06744,5103,17.241379,13.503718,1,1.072145,1.074297,-1,1.067256,-1
99997,1.06742,1.06750,1.06709,1.06730,3513,16.666667,15.250609,1,1.072049,1.074227,-1,1.067276,-1
99998,1.06732,1.06786,1.06731,1.06783,2894,22.495895,18.801314,0,1.071965,1.074163,-1,1.067369,-1
99999,1.06785,1.06807,1.06766,1.06788,2410,26.108374,21.756979,0,1.071884,1.074101,-1,1.067575,-1

In [10]:
df = ti._macd(df)

TypeError: 'int' object does not support item assignment

In [33]:
df

,open,high,low,close,volume,ema_100,ema_200,vwap,vwap_buy_signal,vwap_sell_signal,STOCHk_14_3_3,STOCHd_14_3_3,stochrsi_sell_signal,stochrsi_buy_signal,MACD_12_26_9,macd_buy_signal,macd_sell_signal
0,1.13471,1.13485,1.13396,1.13422,1740,1.134220,1.134220,1.134343,0,1,NaN,NaN,NaN,NaN,NaN,0,0
1,1.13423,1.13462,1.13316,1.13407,2365,1.134217,1.134219,1.134117,0,1,NaN,NaN,NaN,NaN,NaN,0,0
2,1.13407,1.13583,1.13402,1.13563,4016,1.134245,1.134233,1.134633,0,1,NaN,NaN,NaN,NaN,NaN,0,0
3,1.13563,1.13966,1.13562,1.13802,5377,1.134320,1.134270,1.136109,1,0,NaN,NaN,NaN,NaN,NaN,0,0
4,1.13803,1.13833,1.13617,1.13636,4333,1.134360,1.134291,1.136747,0,1,NaN,NaN,NaN,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1.06736,1.06766,1.06709,1.06712,3963,1.072240,1.074366,1.067112,0,1,11.843782,9.664968,0.0,1.0,-0.001400,0,1
99996,1.06712,1.06751,1.06680,1.06744,5103,1.072145,1.074297,1.067256,0,1,17.241379,13.503718,0.0,1.0,-0.001348,0,1
99997,1.06742,1.06750,1.06709,1.06730,3513,1.072049,1.074227,1.067276,0,1,16.666667,15.250609,0.0,1.0,-0.001303,0,1
99998,1.06732,1.06786,1.06731,1.06783,2894,1.071965,1.074163,1.067369,0,1,22.495895,18.801314,0.0,0.0,-0.001211,1,0
99999,1.06785,1.06807,1.06766,1.06788,2410,1.071884,1.074101,1.067575,0,1,26.108374,21.756979,0.0,0.0,-0.001121,1,0

In [34]:
df.dtypes

open                    float64
high                    float64
low                     float64
close                   float64
volume                    int64
ema_100                 float64
ema_200                 float64
vwap                    float64
vwap_buy_signal           int32
vwap_sell_signal          int32
STOCHk_14_3_3           float64
STOCHd_14_3_3           float64
stochrsi_sell_signal    float64
stochrsi_buy_signal     float64
MACD_12_26_9            float64
macd_buy_signal           int32
macd_sell_signal          int32
dtype: object

In [39]:
df = df.dropna()
df.reset_index(inplace=True)

In [40]:
df

,index,open,high,low,close,volume,ema_100,ema_200,vwap,vwap_buy_signal,vwap_sell_signal,STOCHk_14_3_3,STOCHd_14_3_3,stochrsi_sell_signal,stochrsi_buy_signal,MACD_12_26_9,macd_buy_signal,macd_sell_signal
0,25,1.14787,1.14988,1.14739,1.14969,3559,1.137300,1.135901,1.147391,1,0,92.590123,87.629769,0,0,0.003139,0,0
1,26,1.14971,1.14971,1.14716,1.14751,3701,1.137502,1.136017,1.148113,0,1,86.161199,88.599911,1,0,0.003151,0,0
2,27,1.14753,1.14776,1.14678,1.14741,2566,1.137698,1.136130,1.148227,0,1,84.403101,87.718141,1,0,0.003116,0,0
3,28,1.14741,1.14773,1.14701,1.14771,1618,1.137896,1.136245,1.147731,0,1,77.879826,82.814709,0,0,0.003077,0,0
4,29,1.14771,1.14876,1.14761,1.14860,1909,1.138108,1.136368,1.147676,0,1,79.974148,80.752358,0,0,0.003083,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99970,99995,1.06736,1.06766,1.06709,1.06712,3963,1.072240,1.074366,1.067112,0,1,11.843782,9.664968,0,1,-0.001400,0,1
99971,99996,1.06712,1.06751,1.06680,1.06744,5103,1.072145,1.074297,1.067256,0,1,17.241379,13.503718,0,1,-0.001348,0,1
99972,99997,1.06742,1.06750,1.06709,1.06730,3513,1.072049,1.074227,1.067276,0,1,16.666667,15.250609,0,1,-0.001303,0,1
99973,99998,1.06732,1.06786,1.06731,1.06783,2894,1.071965,1.074163,1.067369,0,1,22.495895,18.801314,0,0,-0.001211,1,0
99974,99999,1.06785,1.06807,1.06766,1.06788,2410,1.071884,1.074101,1.067575,0,1,26.108374,21.756979,0,0,-0.001121,1,0

In [37]:
df['stochrsi_sell_signal'] = df['stochrsi_sell_signal'].apply(np.int64)
df['stochrsi_buy_signal'] = df['stochrsi_buy_signal'].apply(np.int64)

C:\Users\singh\AppData\Local\Temp\ipykernel_4292\2890072043.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['stochrsi_sell_signal'] = df['stochrsi_sell_signal'].apply(np.int64)
C:\Users\singh\AppData\Local\Temp\ipykernel_4292\2890072043.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['stochrsi_buy_signal'] = df['stochrsi_buy_signal'].apply(np.int64)

In [44]:
df = df.drop('index',axis=1)

In [45]:
df

,open,high,low,close,volume,ema_100,ema_200,vwap,vwap_buy_signal,vwap_sell_signal,STOCHk_14_3_3,STOCHd_14_3_3,stochrsi_sell_signal,stochrsi_buy_signal,MACD_12_26_9,macd_buy_signal,macd_sell_signal
0,1.14787,1.14988,1.14739,1.14969,3559,1.137300,1.135901,1.147391,1,0,92.590123,87.629769,0,0,0.003139,0,0
1,1.14971,1.14971,1.14716,1.14751,3701,1.137502,1.136017,1.148113,0,1,86.161199,88.599911,1,0,0.003151,0,0
2,1.14753,1.14776,1.14678,1.14741,2566,1.137698,1.136130,1.148227,0,1,84.403101,87.718141,1,0,0.003116,0,0
3,1.14741,1.14773,1.14701,1.14771,1618,1.137896,1.136245,1.147731,0,1,77.879826,82.814709,0,0,0.003077,0,0
4,1.14771,1.14876,1.14761,1.14860,1909,1.138108,1.136368,1.147676,0,1,79.974148,80.752358,0,0,0.003083,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99970,1.06736,1.06766,1.06709,1.06712,3963,1.072240,1.074366,1.067112,0,1,11.843782,9.664968,0,1,-0.001400,0,1
99971,1.06712,1.06751,1.06680,1.06744,5103,1.072145,1.074297,1.067256,0,1,17.241379,13.503718,0,1,-0.001348,0,1
99972,1.06742,1.06750,1.06709,1.06730,3513,1.072049,1.074227,1.067276,0,1,16.666667,15.250609,0,1,-0.001303,0,1
99973,1.06732,1.06786,1.06731,1.06783,2894,1.071965,1.074163,1.067369,0,1,22.495895,18.801314,0,0,-0.001211,1,0
99974,1.06785,1.06807,1.06766,1.06788,2410,1.071884,1.074101,1.067575,0,1,26.108374,21.756979,0,0,-0.001121,1,0

In [46]:
print(df.columns.to_list)

<bound method IndexOpsMixin.tolist of Index(['open', 'high', 'low', 'close', 'volume', 'ema_100', 'ema_200', 'vwap',
       'vwap_buy_signal', 'vwap_sell_signal', 'STOCHk_14_3_3', 'STOCHd_14_3_3',
       'stochrsi_sell_signal', 'stochrsi_buy_signal', 'MACD_12_26_9',
       'macd_buy_signal', 'macd_sell_signal'],
      dtype='object')>

In [49]:
df['Trend'] = 0
df = df.drop('Trend', axis=1)

In [50]:
df['pct_change'] = df['close'].pct_change()

# set the threshold for a trend change (0.16% in this case)
threshold = 0.0016

# create a function to map the percentage change to a trend value
def get_trend(pct_change):
    if pct_change > threshold:
        return 1  # uptrend
    elif pct_change < -threshold:
        return -1  # downtrend
    else:
        return 0  # no change

# apply the get_trend function to the pct_change column to create the trend column
df['trend'] = df['pct_change'].apply(get_trend)

# drop the pct_change column if you don't need it anymore
df.drop('pct_change', axis=1, inplace=True)

In [51]:
df

,open,high,low,close,volume,ema_100,ema_200,vwap,vwap_buy_signal,vwap_sell_signal,STOCHk_14_3_3,STOCHd_14_3_3,stochrsi_sell_signal,stochrsi_buy_signal,MACD_12_26_9,macd_buy_signal,macd_sell_signal,trend
0,1.14787,1.14988,1.14739,1.14969,3559,1.137300,1.135901,1.147391,1,0,92.590123,87.629769,0,0,0.003139,0,0,0
1,1.14971,1.14971,1.14716,1.14751,3701,1.137502,1.136017,1.148113,0,1,86.161199,88.599911,1,0,0.003151,0,0,-1
2,1.14753,1.14776,1.14678,1.14741,2566,1.137698,1.136130,1.148227,0,1,84.403101,87.718141,1,0,0.003116,0,0,0
3,1.14741,1.14773,1.14701,1.14771,1618,1.137896,1.136245,1.147731,0,1,77.879826,82.814709,0,0,0.003077,0,0,0
4,1.14771,1.14876,1.14761,1.14860,1909,1.138108,1.136368,1.147676,0,1,79.974148,80.752358,0,0,0.003083,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99970,1.06736,1.06766,1.06709,1.06712,3963,1.072240,1.074366,1.067112,0,1,11.843782,9.664968,0,1,-0.001400,0,1,0
99971,1.06712,1.06751,1.06680,1.06744,5103,1.072145,1.074297,1.067256,0,1,17.241379,13.503718,0,1,-0.001348,0,1,0
99972,1.06742,1.06750,1.06709,1.06730,3513,1.072049,1.074227,1.067276,0,1,16.666667,15.250609,0,1,-0.001303,0,1,0
99973,1.06732,1.06786,1.06731,1.06783,2894,1.071965,1.074163,1.067369,0,1,22.495895,18.801314,0,0,-0.001211,1,0,0
99974,1.06785,1.06807,1.06766,1.06788,2410,1.071884,1.074101,1.067575,0,1,26.108374,21.756979,0,0,-0.001121,1,0,0